In [1]:
# data manipulation
import numpy as np
import pandas as pd
# decomposition
from sklearn.decomposition import PCA
# encoding labels
from sklearn.preprocessing import LabelEncoder
# scaler
from sklearn.preprocessing import StandardScaler

In [2]:
ds = ['emodb', 'emovo', 'ravdess']

In [3]:
md = {}
for d in ds:
    # md[d] = pd.read_csv(f"/datasets/nicolas_facchinetti/processed_data/{d}/metadata_pre_aug.csv")
    
    md[d] = pd.read_csv(f"D:\\Scuola\\TesiMag\\thesis_adversarial_ml_audio\\processed_data/{d}/metadata_pre_aug.csv")

In [4]:
md['emodb']

,path,filename,chunk,label,actor,gender
0,D:\Scuola\TesiMag\thesis_adversarial_ml_audio\...,03a01Fa.wav,0,happy,3,m
1,D:\Scuola\TesiMag\thesis_adversarial_ml_audio\...,03a01Nc.wav,0,neutral,3,m
2,D:\Scuola\TesiMag\thesis_adversarial_ml_audio\...,03a01Wa.wav,0,angry,3,m
3,D:\Scuola\TesiMag\thesis_adversarial_ml_audio\...,03a02Fc.wav,0,happy,3,m
4,D:\Scuola\TesiMag\thesis_adversarial_ml_audio\...,03a02Nc.wav,0,neutral,3,m
...,...,...,...,...,...,...
675,D:\Scuola\TesiMag\thesis_adversarial_ml_audio\...,16b10Tb.wav,1,sad,16,f
676,D:\Scuola\TesiMag\thesis_adversarial_ml_audio\...,16b10Td.wav,0,sad,16,f
677,D:\Scuola\TesiMag\thesis_adversarial_ml_audio\...,16b10Td.wav,1,sad,16,f
678,D:\Scuola\TesiMag\thesis_adversarial_ml_audio\...,16b10Wa.wav,0,angry,16,f
679,D:\Scuola\TesiMag\thesis_adversarial_ml_audio\...,16b10Wb.wav,0,angry,16,f

In [5]:
sgrams = {}
for d in ds:
    # sgrams[d] = np.load(f"/datasets/nicolas_facchinetti/processed_data/{d}/sgram_pre_aug.npy")
    sgrams[d] = sgram_ravdess = np.load(f"D:\\Scuola\\TesiMag\\thesis_adversarial_ml_audio\\processed_data/{d}/sgram_pre_aug.npy")

np.shape(sgrams['emodb'])

(680, 128, 261)

Since the samples are in tabular form, flatten each samples' matrix to a row. Also standardize the data

In [6]:
for d in ds:
    sgrams[d] = [sample.flatten() for sample in sgrams[d]]
    scaler = StandardScaler()
    sgrams[d] = scaler.fit_transform(sgrams[d])

Extract principal components

In [7]:
def get_components(logmelspectrograms):
    # apply PCA to data
    pca = PCA(0.9)
    principalComponents = pca.fit_transform(logmelspectrograms)
    print(f"Number of extracted components {pca.n_components_}")
    return principalComponents

In [8]:
pc = {}
for d in ds:
    print(f'For {d}')
    pc[d] = get_components(sgrams[d])

For emodb
Number of extracted components 256
For emovo
Number of extracted components 168
For ravdess
Number of extracted components 156

In [30]:
pd.DataFrame(pc['emodb'])

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
0,6.704258,-12.935606,12.239922,-1.823328,-13.023678,12.528459,-1.426997,-26.451353,-13.972350,-6.923877,...,-7.198809,-2.426449,-6.445312,0.366902,0.185197,-0.033776,-0.529775,7.905511,0.867501,0.630911
1,-44.777128,24.557869,24.809838,-10.369508,23.730851,-23.329792,26.968961,-28.249992,-23.206078,-2.901540,...,-0.974021,3.491282,0.951496,1.590075,-2.278326,5.329698,-3.626698,0.251079,1.258400,-1.737985
2,-125.965896,-23.769722,3.604312,-11.292047,-2.831497,14.063264,-8.347938,-16.450558,-17.063679,-10.773771,...,0.621345,0.067350,-2.177975,-4.058167,-4.027651,-0.273644,4.236600,10.537006,1.665450,1.561338
3,-63.853848,-20.340623,1.720915,-1.953036,-1.058965,-11.244658,-11.652970,4.777611,-5.244651,-5.364580,...,-10.730686,-3.561279,-0.272890,2.914670,-6.389990,-0.259230,1.202815,5.548849,-2.837197,-2.824683
4,-63.039653,32.797682,5.852288,8.325409,-6.492689,2.391284,21.434100,5.169494,-0.287307,7.331802,...,0.699906,1.301932,-2.469926,1.038229,1.384024,-0.556325,1.140037,5.004455,-2.045978,-0.567116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675,168.430211,15.254735,-4.603943,50.831695,-4.026559,6.460254,9.227725,8.517699,-1.849760,-6.074175,...,-2.301222,-1.906905,0.335575,-0.963724,-2.867985,1.607883,2.724097,-2.905557,-2.708881,-3.165475
676,-10.417721,-2.925881,-19.806083,4.434685,-4.127645,-1.433182,-3.670496,-9.623952,-1.749489,4.810280,...,0.624141,1.472421,1.385025,-0.440925,0.437868,2.224652,0.569565,-1.465807,-0.860226,-0.814723
677,90.885805,31.031345,-10.392410,21.068660,0.861211,3.178620,-0.812044,-2.255599,10.026473,-6.880023,...,2.380851,-3.365943,1.382550,0.688533,0.859143,2.875013,1.714299,0.326198,0.883639,1.731603
678,138.112460,-65.149215,-12.482755,5.394127,30.965283,8.476718,20.898290,-14.259435,3.761235,1.529541,...,5.058018,-3.749634,-6.510175,-3.462132,-1.631418,-2.589791,-2.910939,3.714251,7.544677,-13.713904
679,-42.928350,-43.171441,-14.220715,1.411067,0.017531,20.381306,-2.798445,1.626133,0.934263,-27.578234,...,0.812246,1.802233,-0.411695,-5.520730,3.313226,3.002470,-0.884583,-5.097878,-3.632235,3.138230

In [23]:
pc['emodb'].shape

(680, 256)

In [26]:
np.transpose(pc['emodb']).shape

(256, 680)

In [32]:
labels = md['emodb'].label
df = pd.DataFrame(pc['emodb'])
df['label'] = labels
df

,0,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,label
0,6.704258,-12.935606,12.239922,-1.823328,-13.023678,12.528459,-1.426997,-26.451353,-13.972350,-6.923877,...,-2.426449,-6.445312,0.366902,0.185197,-0.033776,-0.529775,7.905511,0.867501,0.630911,happy
1,-44.777128,24.557869,24.809838,-10.369508,23.730851,-23.329792,26.968961,-28.249992,-23.206078,-2.901540,...,3.491282,0.951496,1.590075,-2.278326,5.329698,-3.626698,0.251079,1.258400,-1.737985,neutral
2,-125.965896,-23.769722,3.604312,-11.292047,-2.831497,14.063264,-8.347938,-16.450558,-17.063679,-10.773771,...,0.067350,-2.177975,-4.058167,-4.027651,-0.273644,4.236600,10.537006,1.665450,1.561338,angry
3,-63.853848,-20.340623,1.720915,-1.953036,-1.058965,-11.244658,-11.652970,4.777611,-5.244651,-5.364580,...,-3.561279,-0.272890,2.914670,-6.389990,-0.259230,1.202815,5.548849,-2.837197,-2.824683,happy
4,-63.039653,32.797682,5.852288,8.325409,-6.492689,2.391284,21.434100,5.169494,-0.287307,7.331802,...,1.301932,-2.469926,1.038229,1.384024,-0.556325,1.140037,5.004455,-2.045978,-0.567116,neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675,168.430211,15.254735,-4.603943,50.831695,-4.026559,6.460254,9.227725,8.517699,-1.849760,-6.074175,...,-1.906905,0.335575,-0.963724,-2.867985,1.607883,2.724097,-2.905557,-2.708881,-3.165475,sad
676,-10.417721,-2.925881,-19.806083,4.434685,-4.127645,-1.433182,-3.670496,-9.623952,-1.749489,4.810280,...,1.472421,1.385025,-0.440925,0.437868,2.224652,0.569565,-1.465807,-0.860226,-0.814723,sad
677,90.885805,31.031345,-10.392410,21.068660,0.861211,3.178620,-0.812044,-2.255599,10.026473,-6.880023,...,-3.365943,1.382550,0.688533,0.859143,2.875013,1.714299,0.326198,0.883639,1.731603,sad
678,138.112460,-65.149215,-12.482755,5.394127,30.965283,8.476718,20.898290,-14.259435,3.761235,1.529541,...,-3.749634,-6.510175,-3.462132,-1.631418,-2.589791,-2.910939,3.714251,7.544677,-13.713904,angry
679,-42.928350,-43.171441,-14.220715,1.411067,0.017531,20.381306,-2.798445,1.626133,0.934263,-27.578234,...,1.802233,-0.411695,-5.520730,3.313226,3.002470,-0.884583,-5.097878,-3.632235,3.138230,angry

In [34]:
df.groupby(['label']).mean()

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
label,,,,,,,,,,,,,,,,,,,,,
angry,-3.820740,-33.761810,1.569704,-2.821827,1.038903,1.447395,1.825969,3.562342,-1.574660,0.223764,...,0.211433,-0.176955,0.089604,-0.036658,0.152927,0.090453,0.085214,0.105686,0.002346,0.136686
bored,21.324467,25.304497,6.535746,2.274568,-3.849806,1.190107,1.239639,0.006635,1.100089,0.231163,...,0.042790,-0.175297,-0.228213,0.299402,0.103252,-0.214959,0.320276,0.001167,-0.451589,0.021842
disgust,-6.451041,-3.188837,4.862647,9.799787,-2.356127,-3.611405,-2.404834,-3.737932,1.197292,0.617984,...,-0.111405,-0.752206,-0.206359,-0.126811,-0.029963,-0.144283,-0.394159,-0.720966,0.793125,0.168424
fear,-46.261786,-4.205156,-1.546632,2.228476,2.823813,-3.397340,-1.164878,-1.876820,1.761819,1.038197,...,-0.689722,0.814858,0.641067,0.061440,0.206326,-0.166669,-0.045164,0.147848,-0.252620,0.462280
happy,-5.739398,-22.159532,3.251542,1.635087,-0.350416,0.597716,-1.896325,-1.739718,-1.671012,-0.295226,...,0.279853,0.671094,-0.288731,0.141768,-0.050195,-0.001455,0.402265,0.125390,-0.191270,-0.619216
neutral,-7.241525,22.765553,8.602459,2.596084,2.626654,1.470436,1.139260,-1.007157,1.063569,-1.576466,...,0.168711,0.015086,-0.223263,-0.154584,-0.524707,0.075097,-0.515428,-0.097109,0.123828,-0.428006
sad,28.005884,24.473570,-19.195415,-8.813189,0.089969,-0.326228,-0.929984,0.698833,-0.361434,-0.115235,...,-0.152977,-0.175295,0.194216,-0.183592,0.025024,0.217669,-0.053294,0.173605,0.160331,0.186604

In [36]:
df.groupby(['label']).mean().transpose().corr()

label       angry     bored   disgust      fear     happy   neutral       sad
label
angry    1.000000 -0.758648  0.077970  0.171004  0.805529 -0.735701 -0.612133
bored   -0.758648  1.000000 -0.267307 -0.658770 -0.725756  0.453386  0.672525
disgust  0.077970 -0.267307  1.000000  0.310002  0.249653 -0.016640 -0.470904
fear     0.171004 -0.658770  0.310002  1.000000  0.260133  0.171039 -0.667903
happy    0.805529 -0.725756  0.249653  0.260133  1.000000 -0.592800 -0.694228
neutral -0.735701  0.453386 -0.016640  0.171039 -0.592800  1.000000  0.080783
sad     -0.612133  0.672525 -0.470904 -0.667903 -0.694228  0.080783  1.000000

In [37]:
dfs = {}

for d in ds:
    labels = md[d].label
    df = pd.DataFrame(pc['emodb'])
    df['label'] = labels
    dfs[d] = df.groupby(['label']).mean().transpose().corr()

In [38]:
dfs['emodb']

label       angry     bored   disgust      fear     happy   neutral       sad
label
angry    1.000000 -0.758648  0.077970  0.171004  0.805529 -0.735701 -0.612133
bored   -0.758648  1.000000 -0.267307 -0.658770 -0.725756  0.453386  0.672525
disgust  0.077970 -0.267307  1.000000  0.310002  0.249653 -0.016640 -0.470904
fear     0.171004 -0.658770  0.310002  1.000000  0.260133  0.171039 -0.667903
happy    0.805529 -0.725756  0.249653  0.260133  1.000000 -0.592800 -0.694228
neutral -0.735701  0.453386 -0.016640  0.171039 -0.592800  1.000000  0.080783
sad     -0.612133  0.672525 -0.470904 -0.667903 -0.694228  0.080783  1.000000

In [46]:
dfs['emovo']

label,angry,disgust,fear,happy,neutral,sad,surprised
label,,,,,,,
angry,1.000000,0.257143,0.066699,-0.272087,-0.481026,-0.351575,-0.179803
disgust,0.257143,1.000000,0.403313,-0.378397,-0.667902,-0.670186,-0.070165
fear,0.066699,0.403313,1.000000,-0.379122,-0.489136,-0.452406,-0.243316
happy,-0.272087,-0.378397,-0.379122,1.000000,0.147932,0.081718,0.077680
neutral,-0.481026,-0.667902,-0.489136,0.147932,1.000000,0.496658,-0.098818
sad,-0.351575,-0.670186,-0.452406,0.081718,0.496658,1.000000,-0.204587
surprised,-0.179803,-0.070165,-0.243316,0.077680,-0.098818,-0.204587,1.000000

In [40]:
dfs['ravdess']

label,angry,calm,disgust,fear,happy,neutral,sad,surprised
label,,,,,,,,
angry,1.000000,0.007789,-0.490811,0.437713,-0.486337,-0.512445,-0.108955,0.079590
calm,0.007789,1.000000,-0.191243,-0.029704,-0.147302,-0.103838,-0.240769,-0.063551
disgust,-0.490811,-0.191243,1.000000,-0.459173,0.317295,0.351451,-0.082928,-0.259472
fear,0.437713,-0.029704,-0.459173,1.000000,-0.782058,-0.802047,0.044533,0.108474
happy,-0.486337,-0.147302,0.317295,-0.782058,1.000000,0.687342,-0.179027,-0.300042
neutral,-0.512445,-0.103838,0.351451,-0.802047,0.687342,1.000000,-0.154142,-0.236369
sad,-0.108955,-0.240769,-0.082928,0.044533,-0.179027,-0.154142,1.000000,-0.171623
surprised,0.079590,-0.063551,-0.259472,0.108474,-0.300042,-0.236369,-0.171623,1.000000

In [41]:
dfs['emodb'].sum()

label
angry     -0.051978
bored     -0.284569
disgust    0.882775
fear       0.585507
happy      0.302531
neutral    0.360068
sad       -0.691859
dtype: float64

With absolute value in of correlations

In [50]:
mean_corr = {}
for d in ds:
    mean_corr[d] = dfs[d].abs().sum().divide(other=len(dfs[d]))

In [52]:
mean_corr['emodb']

label
angry      0.594426
bored      0.648056
disgust    0.341782
fear       0.462693
happy      0.618300
neutral    0.435764
sad        0.599782
dtype: float64

In [53]:
mean_corr['emovo']

label
angry        0.372619
disgust      0.492444
fear         0.433427
happy        0.333848
neutral      0.483068
sad          0.465304
surprised    0.267767
dtype: float64

In [54]:
mean_corr['ravdess']

label
angry        0.390455
calm         0.223024
disgust      0.394047
fear         0.457963
happy        0.487425
neutral      0.480954
sad          0.247747
surprised    0.277390
dtype: float64

Without abs

In [55]:
mean_corr = {}
for d in ds:
    mean_corr[d] = dfs[d].sum().divide(other=len(dfs[d]))

In [56]:
mean_corr['emodb']

label
angry     -0.007425
bored     -0.040653
disgust    0.126111
fear       0.083644
happy      0.043219
neutral    0.051438
sad       -0.098837
dtype: float64

In [57]:
mean_corr['emovo']

label
angry        0.005622
disgust     -0.018027
fear        -0.013424
happy        0.039675
neutral     -0.013185
sad         -0.014340
surprised    0.040142
dtype: float64

In [58]:
mean_corr['ravdess']

label
angry       -0.009182
calm         0.028923
disgust      0.023140
fear        -0.060283
happy        0.013734
neutral      0.028744
sad          0.013386
surprised    0.019626
dtype: float64